name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      # Set up Flutter.
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter doctor -v
    - name: Checkout flutter_app code
      uses: actions/checkout@v3
    - run: flutter pub get
    - run: flutter build web --web-renderer canvaskit --release
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: build/web
  deploy_web:
    runs-on: ubuntu-latest
    needs: build_web
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
          path: web-build
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_ACTION_APP }}'
          channelId: live
          projectId: github-action-app
